### ISSUE TITLE
Optimise order of watering plants

### ISSUE THREAD

**Issue by derletztename** [etcipnja/MLH#3]
At least on my bot the farmbot moves not in an efficient manner over the field and therefor wasting time and energy. Could something like a Nearest-Neighbour-Heuristik be implemented? Or maybe just go from X axis 0 to max watering all plants that need watering in "rows" of y axis?

**Comment by etcipnja** [comment]
Thank you for feedback! 
I recently added sorting by plant name first. This is a reason of inefficient movement. I think I'll be able to remove it as sorting by name is only needed in a new feature where I want to water several small plants (like Carrots) nonstop (i.e. without turning off water). The fix will be available in couple of days.

**Comment by derletztename** [comment]
Thank you etcipnja :)

**Comment by etcipnja** [comment]
should be fixed in 2.4.1 (master)
https://raw.githubusercontent.com/etcipnja/MLH/master/MLH/manifest.json

**Comment by derletztename** [comment]
Awesome, thx etcipnja :)
Do I have to "install" it again in the farmbot web app or will it work automatically?

**Comment by etcipnja** [comment]
it depends if you are on master or dev branch. Try to update what you have and if you don't see 2.4.1 - install new

**Comment by derletztename** [comment]
Hello Eugene
I am very sorry to kind of reopen this old issue. At least on my farmbot it seems still very inefficient the way the bot drives around the field. I guess it goes through by plant name doing one kind of plant after another?
Couldn't it be changed to start at x axis 0 (home) and then moves in y axis movements to x axis max? I would assume this is a lot faster and energy efficient.
This is extremely important for me, as the farmbot is very off grid and powered by solar power (wind energy will follow soon - in germany there is usually more wind than sun).
If you are interested we could collaborate on this via any chat program your prefer
Best regards
Paul

PS: I haven't written before as I had huge troubles to get my farmbot working at all. X axis was always stalling. Now it seems to work and now the efficiency issue is coming up again ;)
